"""Data models for HL7 Community Digest."""

from datetime import datetime
from enum import Enum
from typing import Optional

from pydantic import BaseModel, Field


class SourceType(str, Enum):
    """Type of content source."""
    
    CONFLUENCE = "confluence"
    ZULIP = "zulip"


class ScrapedContent(BaseModel):
    """Content scraped from a source."""
    
    source_type: SourceType
    source_name: str
    work_group: str
    url: str
    title: str
    content: str
    last_modified: Optional[datetime] = None
    scrape_timestamp: datetime = Field(default_factory=datetime.utcnow)
    
    class Config:
        """Pydantic configuration."""
        
        json_encoders = {
            datetime: lambda v: v.isoformat()
        }


class ConfluencePageContent(ScrapedContent):
    """Content from a Confluence page."""
    
    source_type: SourceType = SourceType.CONFLUENCE
    page_id: Optional[str] = None
    space_key: Optional[str] = None
    
    # Meeting-specific fields
    meeting_date: Optional[datetime] = None
    attendees: list[str] = Field(default_factory=list)
    action_items: list[str] = Field(default_factory=list)
    decisions: list[str] = Field(default_factory=list)


class ZulipMessage(BaseModel):
    """A single Zulip message."""
    
    message_id: int
    sender_name: str
    sender_email: str
    content: str
    timestamp: datetime
    topic: str


class ZulipThreadContent(ScrapedContent):
    """Content from a Zulip thread/topic."""
    
    source_type: SourceType = SourceType.ZULIP
    stream_name: str
    stream_id: int
    topic: str
    title: str = ""
    messages: list[ZulipMessage] = Field(default_factory=list)
    participant_count: int = 0
    message_count: int = 0
    content: str = ""  # AI-generated summary content
    recent_message_count: int = 0  # Messages in recent window (24h)
    is_trending: bool = False


class ContentSummary(BaseModel):
    """Summarized content for the digest."""
    
    source_type: SourceType
    source_name: str
    work_group: str
    url: str
    summary: str
    is_trending: bool = False
    has_updates: bool = True
    
    # Optional metadata
    last_activity: Optional[datetime] = None
    participant_count: Optional[int] = None


class DigestSection(BaseModel):
    """A section of the digest (e.g., Confluence or Zulip)."""
    
    title: str
    source_type: SourceType
    summaries: list[ContentSummary] = Field(default_factory=list)


class Digest(BaseModel):
    """Complete daily digest."""
    
    date: datetime
    sections: list[DigestSection] = Field(default_factory=list)
    generated_at: datetime = Field(default_factory=datetime.utcnow)
    
    def to_plain_text(self) -> str:
        """Render digest as plain text email.
        
        Returns:
            Formatted plain text string.
        """
        lines = []
        
        # Header
        date_str = self.date.strftime("%A, %B %d, %Y")
        lines.append("=" * 50)
        lines.append(f"HL7 Community Digest - {date_str}")
        lines.append("=" * 50)
        lines.append("")
        
        # Sections
        for section in self.sections:
            lines.append(section.title.upper())
            lines.append("-" * len(section.title))
            lines.append("")
            
            if not section.summaries:
                lines.append("No updates found.")
                lines.append("")
                continue
            
            # Group by work group
            work_groups: dict[str, list[ContentSummary]] = {}
            for summary in section.summaries:
                if summary.work_group not in work_groups:
                    work_groups[summary.work_group] = []
                work_groups[summary.work_group].append(summary)
            
            for work_group, summaries in work_groups.items():
                lines.append(f"[{work_group}]")
                
                for summary in summaries:
                    # Add trending indicator if applicable
                    trending = " 🔥 Trending" if summary.is_trending else ""
                    
                    if summary.has_updates:
                        lines.append(f"{summary.summary}{trending}")
                        lines.append(f"→ Source: {summary.url}")
                    else:
                        lines.append(f"No new updates since last digest.")
                    
                    lines.append("")
                
            lines.append("")
        
        # Footer
        lines.append("=" * 50)
        lines.append("Generated by HL7 Community Intelligence System")
        lines.append("Questions? Contact: jyounkin.ai@gmail.com")
        lines.append("=" * 50)
        
        return "\n".join(lines)
